SCALE = 1.5
FRAME_W = 16 * SCALE
FRAME_H = 16 * SCALE

WINDOW_W = FRAME_W * 28
WINDOW_H = FRAME_H * 33

PACMAN_SURFACE_W = 26 * SCALE
PACMAN_SURFACE_H = 26 * SCALE
PACMAN_SPEED = 2

# animate
ANIMATE_SPEED = 10 # càng nhỏ hiệu ứng càng nhanh